<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NVCUVC3" ignored="3" name="Native Android App Testing" tests="1" failures="1" timestamp="20 Aug 2017 19:16:54 GMT" time="56.074" errors="0">
  <testcase name="verifyContactNumber" time="8.711" classname="tests.Native_Fab_specs">
    <failure type="java.lang.AssertionError" message="expected [+91704242422] but found [+917042424242]">
      <![CDATA[java.lang.AssertionError: expected [+91704242422] but found [+917042424242]
	at tests.Native_Fab_specs.verifyContactNumber(Native_Fab_specs.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verifyContactNumber -->
  <testcase name="countLocalitiesAndHotels" time="0.0" classname="tests.Native_Fab_specs">
    <ignored/>
  </testcase> <!-- countLocalitiesAndHotels -->
  <testcase name="verifyCoupon" time="0.0" classname="tests.Native_Fab_specs">
    <ignored/>
  </testcase> <!-- verifyCoupon -->
  <testcase name="SearchFormScreenCount" time="0.0" classname="tests.Native_Fab_specs">
    <ignored/>
  </testcase> <!-- SearchFormScreenCount -->
</testsuite> <!-- Native Android App Testing -->
